### ISSUE TITLE
Auto-detect the package manager being used

### ISSUE THREAD

**Issue by dhruwlalan** [maddhruv/types-sync#1]
An attempt to run the install command using a package manager other than npm defaults to run types-sync using npm if not explicitly defined the package manager to be used in the `.types-syncrc.json`  file. 

In the case of yarn, it creates an extry `package-lock.json` file, while in the case of pnpm, it gets hung up.

![undetect](https://user-images.githubusercontent.com/64348100/117096217-08cfef80-ad86-11eb-8966-d9dafcbeb115.png)

It would be nice if the package manager used is auto-detected when the user does not contain the `.types-syncrc.json` file?

**Comment by maddhruv** [comment]
`types-sync` runs as an npm hook script i.e. `prepare`, I am not aware of any mechanism to know the arguments for the parent script (here `install`). Do you know some way with which we can check the exact `install` script which ran, in `prepare` script?

**Comment by dhruwlalan** [comment]
How about this?



Since people working on a project might definitely be working with lockfiles. So we can detect the package manager based on the lockfile.

**Comment by dhruwlalan** [comment]
Since people working on a project might definitely be working with lockfiles. We can then detect the package manager being used based on the lockfile the project has.

Have a look at this:

![detect](https://user-images.githubusercontent.com/64348100/117109496-65410800-ada2-11eb-932e-2dfa95cb39b2.png)

Should I raise a PR?

**Comment by maddhruv** [comment]
Yeah, PRs are always welcome 🤗 
But let's add precedence on the `rc-config` and if the package manager is defined, the cli will use that instead of checking it from the lock files.

**Comment by dhruwlalan** [comment]
Yes, I'll make sure of that.
